/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Productos.Produccion;

import Clases.machusculas;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class agregar_pro_prod extends javax.swing.JDialog {

    /**
     * Creates new form Departamentos
     */
    public agregar_pro_prod(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txt_cant.setDocument(new machusculas());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_cant = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txt_id1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtstock1 = new javax.swing.JTextField();
        btnbuscar2 = new javax.swing.JButton();
        txt_id2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cb_marca = new javax.swing.JComboBox();
        cb_destino = new javax.swing.JComboBox();
        cb_nivel_per = new javax.swing.JComboBox();
        cb_escudo = new javax.swing.JComboBox();
        cb_auspicio = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txt_cant1 = new javax.swing.JTextField();
        txt_cant2 = new javax.swing.JTextField();
        txt_cant3 = new javax.swing.JTextField();
        txt_cant4 = new javax.swing.JTextField();
        txt_cant5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_cant.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cant.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 240, 60, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_4/agrega.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 110, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Id Prod.:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        txt_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_id.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_id.setEnabled(false);
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 340, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Modelo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 30));

        txt_nom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nom.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nom.setEnabled(false);
        jPanel1.add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 340, 30));

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_4/busqueda.png"))); // NOI18N
        btnbuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 50, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Marca:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, 30));

        txt_id1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_id1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_id1.setEnabled(false);
        jPanel1.add(txt_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 120, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Color:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 30));

        txtstock1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstock1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtstock1.setEnabled(false);
        jPanel1.add(txtstock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 200, 30));

        btnbuscar2.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnbuscar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_4/busqueda.png"))); // NOI18N
        btnbuscar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnbuscar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 50, 30));

        txt_id2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_id2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_id2.setEnabled(false);
        jPanel1.add(txt_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 120, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("XXG");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 60, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Destino:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Nivel de pers.:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Escudo:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Auspicio:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, 30));

        cb_marca.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cb_marca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SUBLIMADO", "CATFLEX", "TRANSFER", "TPU", "SILICONA" }));
        jPanel1.add(cb_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 190, 30));

        cb_destino.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cb_destino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "JUGADOR", "ARQUERO", "DT/DF", "PUBLICO", "STOCK" }));
        jPanel1.add(cb_destino, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 190, 30));

        cb_nivel_per.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cb_nivel_per.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SIN PERSONALIZADO", "SOLO NOMBRE", "SOLO NUMERO", "CON NOMBRE Y NUMERO" }));
        jPanel1.add(cb_nivel_per, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 160, 30));

        cb_escudo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cb_escudo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SUBLIMADO", "SUBLIBORDADO", "TRASNFER", "TPU", "BORDADO COMPUTARIZADO", "ETIQUETAS" }));
        jPanel1.add(cb_escudo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 190, 30));

        cb_auspicio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cb_auspicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SUBLIMADO", "CATFLEX", "TRANSFER" }));
        jPanel1.add(cb_auspicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 160, 30));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("XP");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 60, 30));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("P");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 60, 30));

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("M");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 60, 30));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("G");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 60, 30));

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("XG");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 60, 30));

        txt_cant1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cant1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cant1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cant1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cant1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 60, 30));

        txt_cant2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cant2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cant2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cant2ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cant2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 60, 30));

        txt_cant3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cant3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cant3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cant3ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cant3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 60, 30));

        txt_cant4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cant4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cant4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cant4ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cant4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 60, 30));

        txt_cant5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cant5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cant5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cant5ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_cant5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 60, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 370));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (txt_cant.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese una cantidad válida");
        } else {
      

        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed

    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnbuscar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbuscar2ActionPerformed

    private void txt_cantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantActionPerformed

    private void txt_cant1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cant1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cant1ActionPerformed

    private void txt_cant2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cant2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cant2ActionPerformed

    private void txt_cant3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cant3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cant3ActionPerformed

    private void txt_cant4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cant4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cant4ActionPerformed

    private void txt_cant5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cant5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cant5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(agregar_pro_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(agregar_pro_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(agregar_pro_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(agregar_pro_prod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                agregar_pro_prod dialog = new agregar_pro_prod(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnbuscar2;
    private javax.swing.JComboBox cb_auspicio;
    private javax.swing.JComboBox cb_destino;
    private javax.swing.JComboBox cb_escudo;
    private javax.swing.JComboBox cb_marca;
    private javax.swing.JComboBox cb_nivel_per;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_cant;
    private javax.swing.JTextField txt_cant1;
    private javax.swing.JTextField txt_cant2;
    private javax.swing.JTextField txt_cant3;
    private javax.swing.JTextField txt_cant4;
    private javax.swing.JTextField txt_cant5;
    public static javax.swing.JTextField txt_id;
    public static javax.swing.JTextField txt_id1;
    public static javax.swing.JTextField txt_id2;
    public static javax.swing.JTextField txt_nom;
    public static javax.swing.JTextField txtstock1;
    // End of variables declaration//GEN-END:variables

}
