/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Estadisticas_productos;

import Conexion_DB.conectar;
import static Loggin_Principal.NECTTIC.ingreso;
import Loggin_Principal.Principal;
import static Loggin_Principal.Principal.lbl_usu_almacen;
import Productos.items.Categorias_List_marca;
import Productos.items.Departamentos_List_marca;
import Productos.items.Marca_list_marca;
import java.math.BigDecimal;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRExporterParameter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.engine.export.JRPrintServiceExporter;
import net.sf.jasperreports.engine.export.JRPrintServiceExporterParameter;
import net.sf.jasperreports.engine.util.JRLoader;

public class Listado_marcas_pro extends javax.swing.JDialog {

    DefaultTableModel model;
    private static DefaultTableCellRenderer tcr;

    public Listado_marcas_pro(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lbl_almacen_marca.setText(lbl_usu_almacen.getText());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_control = new javax.swing.JTable();
        txt_cant_pro = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_id_dep_salidas = new javax.swing.JTextField();
        txt_nom_dep_salidas = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txt_id_marca = new javax.swing.JTextField();
        txt_nom_marca = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        txt_id_cate = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        txt_nom_cate = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lbl_almacen_marca = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listado por marca");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Departamento:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        btn_buscar.setBackground(new java.awt.Color(255, 255, 255));
        btn_buscar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_4/graphic.png"))); // NOI18N
        btn_buscar.setToolTipText("Buscar");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 20, 60, 50));

        tb_control.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_control.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tb_control.setShowHorizontalLines(false);
        tb_control.setShowVerticalLines(false);
        tb_control.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_controlMouseClicked(evt);
            }
        });
        tb_control.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tb_controlKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(tb_control);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1120, 430));

        txt_cant_pro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_cant_pro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_cant_pro.setText("0");
        txt_cant_pro.setDisabledTextColor(new java.awt.Color(204, 0, 0));
        txt_cant_pro.setEnabled(false);
        jPanel1.add(txt_cant_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 550, 110, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Cantidad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 550, 70, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_4/print.png"))); // NOI18N
        jButton1.setToolTipText("Imprimir");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, 60, 50));

        txt_id_dep_salidas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_id_dep_salidas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_id_dep_salidas.setText("0");
        txt_id_dep_salidas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_id_dep_salidas.setEnabled(false);
        txt_id_dep_salidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_id_dep_salidasMouseClicked(evt);
            }
        });
        jPanel1.add(txt_id_dep_salidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 90, 30));

        txt_nom_dep_salidas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nom_dep_salidas.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nom_dep_salidas.setText("TODOS");
        txt_nom_dep_salidas.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nom_dep_salidas.setEnabled(false);
        jPanel1.add(txt_nom_dep_salidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 370, 30));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_3/lupa.png"))); // NOI18N
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 60, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Marca:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 50, 30));

        txt_id_marca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_id_marca.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_id_marca.setText("0");
        txt_id_marca.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_id_marca.setEnabled(false);
        jPanel1.add(txt_id_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 90, 30));

        txt_nom_marca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nom_marca.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nom_marca.setText("TODOS");
        txt_nom_marca.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nom_marca.setEnabled(false);
        jPanel1.add(txt_nom_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, 370, 30));

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_3/lupa.png"))); // NOI18N
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 70, 60, 30));

        txt_id_cate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_id_cate.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txt_id_cate.setText("0");
        txt_id_cate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_id_cate.setEnabled(false);
        jPanel1.add(txt_id_cate, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 90, 30));

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_3/lupa.png"))); // NOI18N
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 60, 30));

        txt_nom_cate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nom_cate.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_nom_cate.setText("TODOS");
        txt_nom_cate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nom_cate.setEnabled(false);
        jPanel1.add(txt_nom_cate, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 370, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Categoría:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 30));

        lbl_almacen_marca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lbl_almacen_marca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Caja_2/iconos/dpto.png"))); // NOI18N
        lbl_almacen_marca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbl_almacen_marca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lbl_almacen_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_almacen_marcaMouseClicked(evt);
            }
        });
        jPanel1.add(lbl_almacen_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 20, 110, 50));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_4/barriendo.png"))); // NOI18N
        jButton2.setToolTipText("Limpiar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 20, 80, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        Departamentos_List_marca dlm;
        dlm = new Departamentos_List_marca(new javax.swing.JDialog(), true);
        dlm.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        PrintService[] printService = PrintServiceLookup.lookupPrintServices(null, null);
        if (printService.length > 0)//si existen impresoras
        {
            //se elige la impresora
            PrintService impresora = (PrintService) JOptionPane.showInputDialog(null, "Seleccionar  impresora:",
                    "Imprimir ", JOptionPane.QUESTION_MESSAGE, null, printService, printService[0]);
            if (impresora != null) //Si se selecciono una impresora
            {

                Productos_Marca ps;//
                List<Productos_Marca> lista = new ArrayList<>(); //Creamos una lista de empleados con ArrayList para obtener cada empleado
                for (int i = 0; i < tb_control.getRowCount(); i++) { // Iterena cada fila de la tabla
                    ps = new Productos_Marca(tb_control.getValueAt(i, 0).toString(), tb_control.getValueAt(i, 1).toString(), //Tomamos de la tabla el valor de cada columna y creamos un objeto empleado
                            tb_control.getValueAt(i, 2).toString(), tb_control.getValueAt(i, 3).toString());
                    lista.add(ps); //Agregamos el objeto empleado a la lista
                }

                try {

                    String idepa = txt_id_dep_salidas.getText();
                    String desdepa = txt_nom_dep_salidas.getText();
                    String idcate = txt_id_cate.getText();
                    String descate = txt_nom_cate.getText();
                    String idmarca = txt_id_marca.getText();
                    String desmarca = txt_nom_marca.getText();
                    String items = txt_cant_pro.getText();

                    Map parametro = new HashMap();
                    parametro.clear();
                    parametro.put("idepa", idepa);
                    parametro.put("desdepa", desdepa);
                    parametro.put("idcate", idcate);
                    parametro.put("descate", descate);
                    parametro.put("idmarca", idmarca);
                    parametro.put("desmarca", desmarca);
                    parametro.put("items", items);

                    URL in = this.getClass().getResource("/Estadisticas_productos/Pro_Marca.jasper");
                    JasperReport reporte = (JasperReport) JRLoader.loadObject(in);
                    JasperPrint print = JasperFillManager.fillReport(reporte, parametro, new JRBeanCollectionDataSource(lista));

                    JRPrintServiceExporter jrprintServiceExporter = new JRPrintServiceExporter();
                    jrprintServiceExporter.setParameter(JRExporterParameter.JASPER_PRINT, print);
                    jrprintServiceExporter.setParameter(JRPrintServiceExporterParameter.PRINT_SERVICE, impresora);
                    //  jrprintServiceExporter.setParameter(JRPrintServiceExporterParameter.DISPLAY_PRINT_DIALOG, Boolean.TRUE);
                    jrprintServiceExporter.exportReport();
                } catch (JRException ex) {
                    Logger.getLogger(Listado_marcas_pro.class
                            .getName()).log(Level.SEVERE, null, ex);
                }
            }

        }

        // JOptionPane.showMessageDialog(null, "En construcción");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tb_controlKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tb_controlKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_controlKeyReleased

    private void tb_controlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_controlMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_controlMouseClicked

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        String dep = txt_id_dep_salidas.getText();
        String cate = txt_id_cate.getText();
        String marca = txt_id_marca.getText();
        String var = "0";

        if (lbl_almacen_marca.getText().equals("TODOS")) {
            JOptionPane.showMessageDialog(null, "Selecione un Sucursal/Almacén válido");
        } else {

            if (lbl_almacen_marca.getText().equals("0000001")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_cant,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_cant,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_cant,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_cant,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_cant,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_cant,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_cant,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }

            if (lbl_almacen_marca.getText().equals("0000002")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_2,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_2,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_2,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_2,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_2,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_2,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_2,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }

            if (lbl_almacen_marca.getText().equals("0000003")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_3,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_3,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_3,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_3,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_3,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_3,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_3,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000004")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_4,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_4,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_4,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_4,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_4,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_4,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_4,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000005")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_5,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_5,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_5,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_5,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_5,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_5,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_5,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000006")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_6,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_6,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_6,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_6,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_6,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_6,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_6,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000007")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_7,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_7,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_7,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_7,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_7,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_7,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_7,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000008")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_8,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_8,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_8,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_8,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_8,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_8,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_8,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000009")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_9,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_9,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_9,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_9,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_9,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_9,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_9,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000010")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_10,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_10,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_10,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_10,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_10,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_10,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_10,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000011")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_11,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_11,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_11,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_11,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_11,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_11,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_11,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000012")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_12,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_12,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_12,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_12,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_12,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_12,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_12,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000013")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_13,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_13,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_13,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_13,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_13,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_13,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_13,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000014")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_14,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_14,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_14,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_14,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_14,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_14,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_14,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000015")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_15,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_15,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_15,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_15,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_15,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_15,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_15,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000016")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_16,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_16,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_16,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_16,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_16,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_16,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_16,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000017")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_17,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_17,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_17,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_17,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_17,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_17,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_17,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000018")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_18,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_18,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_18,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_18,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_18,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_18,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_18,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000019")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_19,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_19,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_19,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_19,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_19,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_19,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_19,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000020")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_20,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_20,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_20,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_20,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_20,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_20,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_20,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000021")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_21,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_21,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_21,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_21,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_21,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_21,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_21,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000022")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_22,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_22,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_22,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_22,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_22,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_22,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_22,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000023")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_23,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_23,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_23,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_23,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_23,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_23,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_23,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000024")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_24,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_24,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_24,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_24,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_24,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_24,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_24,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000025")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_25,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_25,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_25,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_25,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_25,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_25,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_25,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000026")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_26,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_26,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_26,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_26,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_26,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_26,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_26,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000027")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_27,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_27,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_27,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_27,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_27,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_27,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_27,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000028")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_28,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_28,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_28,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_28,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_28,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_28,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_28,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000029")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_29,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_29,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_29,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_29,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_29,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_29,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_29,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
            if (lbl_almacen_marca.getText().equals("0000030")) {
                if (dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_30,pro_pre_a FROM tienda_productos   ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_30,pro_pre_a FROM tienda_productos where   pro_depa='" + dep + "' ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_30,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "'  AND  pro_cat='" + cate + "'  ORDER BY pro_cod ASC";

                    cargarPro(mostrar);

                } else if (!dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_30,pro_pre_a FROM tienda_productos where    pro_depa='" + dep + "' AND pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } ////segundo casos
                else if (dep.equals(var) && !cate.equals(var) && marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_30,pro_pre_a FROM tienda_productos where      pro_cat='" + cate + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && !cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_30,pro_pre_a FROM tienda_productos where    pro_cat='" + cate + "' AND pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);

                } else if (dep.equals(var) && cate.equals(var) && !marca.equals(var)) {
                    String mostrar = "SELECT pro_cod,pro_des,pro_stock_30,pro_pre_a FROM tienda_productos where     pro_marca='" + marca + "'  ORDER BY pro_cod ASC";
                    cargarPro(mostrar);
                }
            }
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        Marca_list_marca dlm;
        dlm = new Marca_list_marca(new javax.swing.JDialog(), true);
        dlm.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        Categorias_List_marca dlc;
        dlc = new Categorias_List_marca(new javax.swing.JDialog(), true);
        dlc.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txt_id_dep_salidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_id_dep_salidasMouseClicked
        txt_id_dep_salidas.setText("0");
        txt_id_cate.setText("0");
        txt_id_marca.setText("0");
        txt_nom_dep_salidas.setText("TODOS");
        txt_nom_cate.setText("TODOS");
        txt_nom_marca.setText("TODOS");
    }//GEN-LAST:event_txt_id_dep_salidasMouseClicked

    private void lbl_almacen_marcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_almacen_marcaMouseClicked
        if (Principal.lbl_usu_almacen.getText().equals("TODOS")) {

            Almacen_list_marca am;
            am = new Almacen_list_marca(new javax.swing.JDialog(), true);
            am.setVisible(true);

        }
    }//GEN-LAST:event_lbl_almacen_marcaMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txt_id_dep_salidas.setText("0");
        txt_id_cate.setText("0");
        txt_id_marca.setText("0");
        txt_nom_dep_salidas.setText("TODOS");
        txt_nom_cate.setText("TODOS");
        txt_nom_marca.setText("TODOS");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listado_marcas_pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listado_marcas_pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listado_marcas_pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listado_marcas_pro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Listado_marcas_pro dialog = new Listado_marcas_pro(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    public static javax.swing.JLabel lbl_almacen_marca;
    public static javax.swing.JTable tb_control;
    private javax.swing.JTextField txt_cant_pro;
    public static javax.swing.JTextField txt_id_cate;
    public static javax.swing.JTextField txt_id_dep_salidas;
    public static javax.swing.JTextField txt_id_marca;
    public static javax.swing.JTextField txt_nom_cate;
    public static javax.swing.JTextField txt_nom_dep_salidas;
    public static javax.swing.JTextField txt_nom_marca;
    // End of variables declaration//GEN-END:variables

    void cargarPro(String sql) {

        String[] titulos = {"Id Producto", "Nombre", "Cantidad", "Precio Ventas"};
        String[] Registros = new String[13];
        model = new DefaultTableModel(null, titulos);

        try {
            Connection cn = conectar.getInstance().getConnection();

            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Registros[0] = rs.getString(1);
                Registros[1] = rs.getString(2);
                Registros[2] = rs.getString(3);
                Registros[3] = rs.getString(4);

                model.addRow(Registros);
            }

            tb_control.setModel(model);
            tb_control.getColumnModel().getColumn(0).setPreferredWidth(100);
            tb_control.getColumnModel().getColumn(1).setPreferredWidth(250);
            tb_control.getColumnModel().getColumn(2).setPreferredWidth(120);
            tb_control.getColumnModel().getColumn(3).setPreferredWidth(100);

            conectar.getInstance().closeConnection(cn);
            calcularCantidadPro();
        } catch (SQLException ex) {
            Logger.getLogger(Listado_marcas_pro.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void calcularCantidadPro() {

        int Acumulador = 0;
        int TF = tb_control.getRowCount();
        for (int i = 0; i < TF; i++) {
            int CantidadPro = Integer.valueOf(tb_control.getValueAt(i, 2).toString().replaceAll("\\s", "").replaceAll("[^0-9]", ""));
            Acumulador = Acumulador + CantidadPro;
        }
        //</editor-fold>
        txt_cant_pro.setText(MaskaraPrecioUnitarioEnteros(String.valueOf(Acumulador)));

    }

    public String MaskaraPrecioUnitarioEnteros(String ValorGuaranies) {
        DecimalFormat format = new DecimalFormat("###,###.##");
        long NumeroIntacto = 0L;
        String NroFormatado = "";
        String ValorViejo = ValorGuaranies;
        String a = ValorViejo.replace(",", "");
        NumeroIntacto = Long.valueOf(a);
        NroFormatado = format.format(NumeroIntacto);
        String LuzParaMisOjos = NroFormatado;
        return LuzParaMisOjos;
    }

    public void calcularcantida() {

        String impt = "0", subtotalt = "0";

        for (int i = 0; i < tb_control.getRowCount(); i++) {
            BigDecimal PulidoPrec = ingreso.TransformReales(tb_control.getValueAt(i, 3).toString().replaceAll("\\s", ""));

            impt = ingreso.MaskareaRealesDado_String_ExclusiveMonedas(PulidoPrec.toString());
            subtotalt = ingreso.MaskareaRealesDado_String_ExclusiveMonedas(ingreso.TransformReales(subtotalt).add(ingreso.TransformReales(impt)).toString());

            txt_cant_pro.setText(subtotalt);
        }

    }//FIN METODO

}
