/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Conexion_DB;

import Clases.machusculas;
import Compras.visor_compras;
import Loggin_Principal.Principal;
import static Loggin_Principal.Principal.lbl_fecha_hoy;
import static Loggin_Principal.Principal.lbl_usu_nom;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Ajuste_stock_manual extends javax.swing.JDialog {

    /**
     * Creates new form Departamentos
     */
    public Ajuste_stock_manual(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtdes.setDocument(new machusculas());
        if (Principal.lbl_usu_almacen.getText().equals("TODOS")) {
            btn_sucursal.setEnabled(true);
        } else {
            txt_alma_aju.setText(Principal.lbl_usu_almacen.getText());
            btn_sucursal.setEnabled(false);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtdes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_saldo_pro = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_alma_aju = new javax.swing.JTextField();
        btn_sucursal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ajuste de Stock");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtdes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtdesKeyReleased(evt);
            }
        });
        jPanel1.add(txtdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 80, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_4/rehacer.png"))); // NOI18N
        jButton1.setText("Actualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, 120, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Almacén:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 30));

        txt_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_id.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_id.setEnabled(false);
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 120, 30));

        txt_saldo_pro.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txt_saldo_pro.setText("0");
        jPanel1.add(txt_saldo_pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, 50, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Descripción:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        txt_nom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nom.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nom.setEnabled(false);
        jPanel1.add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 410, 30));

        btnbuscar.setBackground(new java.awt.Color(255, 255, 255));
        btnbuscar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnbuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos_2/pallet.png"))); // NOI18N
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(525, 10, 80, 60));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Stock Actual:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        txtstock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstock.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtstock.setEnabled(false);
        jPanel1.add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 80, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Id Producto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        txt_alma_aju.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_alma_aju.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_alma_aju.setEnabled(false);
        jPanel1.add(txt_alma_aju, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 180, 30));

        btn_sucursal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_sucursal.setText("...");
        btn_sucursal.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btn_sucursal.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_sucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sucursalActionPerformed(evt);
            }
        });
        jPanel1.add(btn_sucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 40, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Cantidad existente:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Ref=");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 50, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 190));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        cagada();
        int minimo = 0;
        int stock = Integer.parseInt(txtdes.getText());

        if (stock < minimo || txtdes.getText() == null) {

            JOptionPane.showMessageDialog(null, "Ingrese un valor válido");
        } else {

            if (txt_alma_aju.getText().equals("TODOS")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_cant = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();

                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000001")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_cant = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }

            if (txt_alma_aju.getText().equals("0000002")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_2 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000003")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_3 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000004")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_4 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000005")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_5 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            ////nuevos depositos
            if (txt_alma_aju.getText().equals("0000006")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_6 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000007")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_7 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000008")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_8 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000009")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_9 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000010")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_10 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000011")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_11 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000012")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_12 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000013")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_13 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000014")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_14 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000015")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_15 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000016")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_16 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000017")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_17 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000018")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_18 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000019")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_19 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000020")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_20 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000021")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_21 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000022")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_22 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000023")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_23 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000024")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_24 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000025")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_25 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000026")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_26 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000027")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_27 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000028")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_28 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }
            if (txt_alma_aju.getText().equals("0000029")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_29 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }
            }
            if (txt_alma_aju.getText().equals("0000030")) {
                try {
                    String id = txt_id.getText();
                    String des = txtdes.getText();
                    String sql = "UPDATE tienda_productos SET pro_stock_30 = '" + des
                            + "' WHERE pro_cod = '" + id + "'";
                    try {
                        Connection cn = conectar.getInstance().getConnection();

                        PreparedStatement pst = cn.prepareStatement(sql);
                        pst.executeUpdate();
                        conectar.getInstance().closeConnection(cn);

                        JOptionPane.showMessageDialog(null, "Actualizado, Stock actual=" + des);
                        limpiar();
                    } catch (SQLException | HeadlessException e) {
                        JOptionPane.showMessageDialog(null, e);
                    }

                } catch (Exception e) {
                }

            }

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        Productos_buscar ecv;
        ecv = new Productos_buscar(new javax.swing.JDialog(), true);
        ecv.setVisible(true);
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btn_sucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sucursalActionPerformed
        if (Principal.lbl_usu_almacen.getText().equals("TODOS")) {
            limpiar();
            Ajuste_almacen am;
            am = new Ajuste_almacen(new javax.swing.JDialog(), true);
            am.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "No cuenta con autorización");
        }

    }//GEN-LAST:event_btn_sucursalActionPerformed

    private void txtdesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdesKeyReleased
        int stock = Integer.parseInt(txtstock.getText());

        if (stock < 0) {
            JOptionPane.showMessageDialog(null, "Ingrese una nro válido o mayor que o igual 0");
        } else {
            try {
                int ajuste = Integer.parseInt(txtdes.getText());
                int suma = stock + ajuste;
                String saldo = String.valueOf(suma);
                txt_saldo_pro.setText(saldo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ingrese una nro válido o mayor que o igual 0");
                txtdes.setText("");
                txt_saldo_pro.setText("0");
            }

        }

    }//GEN-LAST:event_txtdesKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajuste_stock_manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajuste_stock_manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajuste_stock_manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajuste_stock_manual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ajuste_stock_manual dialog = new Ajuste_stock_manual(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_sucursal;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JTextField txt_alma_aju;
    public static javax.swing.JTextField txt_id;
    public static javax.swing.JTextField txt_nom;
    private javax.swing.JLabel txt_saldo_pro;
    private javax.swing.JTextField txtdes;
    public static javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables

    void limpiar() {

        txt_id.setText("");
        txt_nom.setText("");
        txtdes.setText("0");
        txtstock.setText("0");
        txt_saldo_pro.setText("");
    }

    void cagada() {
        String InsertarSQL = "INSERT INTO cagada(usu_cag,modulo_cag,ope_cag,data_cag) VALUES (?,?,?,?)";

        String user = lbl_usu_nom.getText();
        String modulo = ("Ajuste de stock de Nro= " + txt_alma_aju.getText());
        String operacion = ("ID-" + txt_id.getText() + "=" + "CANT=" + txtdes.getText() + " CANT ANT=" + txtstock.getText() + " REF=" + txt_saldo_pro.getText());
        String fecha_caja = lbl_fecha_hoy.getText();
        try {
            Connection cn = conectar.getInstance().getConnection();

            PreparedStatement pst = cn.prepareStatement(InsertarSQL);
            pst.setString(1, user);
            pst.setString(2, modulo);
            pst.setString(3, operacion);
            pst.setString(4, fecha_caja);

            int n = pst.executeUpdate();
            conectar.getInstance().closeConnection(cn);

            if (n > 0) {
                //JOptionPane.showMessageDialog(null, "Los datos se guardaron correctamente");
            }

        } catch (SQLException ex) {
            Logger.getLogger(visor_compras.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

}
