/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas.Fact_surc_26;


import Clases.GenerarNumero;
import Conexion_DB.conectar;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto
 */
public class parametro_cambio_26 extends javax.swing.JDialog {

    /**
     * Creates new form printers
     */
    public parametro_cambio_26(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_ok_para = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        txt_nro_fact = new javax.swing.JTextField();
        txt_seq_cambio = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txt_nro_timbra = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Parámetros de factura");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_ok_para.setBackground(new java.awt.Color(255, 255, 255));
        btn_ok_para.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btn_ok_para.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_4/check.png"))); // NOI18N
        btn_ok_para.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ok_para.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ok_paraMouseClicked(evt);
            }
        });
        btn_ok_para.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ok_paraActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ok_para, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 70, 40));

        jLabel22.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel22.setText("Timbrado:");
        jLabel22.setFocusable(false);
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 70, 30));

        txt_nro_fact.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_nro_fact.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_nro_fact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nro_factActionPerformed(evt);
            }
        });
        txt_nro_fact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_nro_factKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nro_factKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_nro_factKeyTyped(evt);
            }
        });
        jPanel1.add(txt_nro_fact, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 120, 30));

        txt_seq_cambio.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_seq_cambio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_seq_cambioMouseClicked(evt);
            }
        });
        txt_seq_cambio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_seq_cambioKeyTyped(evt);
            }
        });
        jPanel1.add(txt_seq_cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 70, 30));

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Nro de sequencia:");
        jLabel23.setFocusable(false);
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 30));

        txt_nro_timbra.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jPanel1.add(txt_nro_timbra, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 130, 30));

        jLabel24.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel24.setText("Nro de factura:");
        jLabel24.setFocusable(false);
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ok_paraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ok_paraActionPerformed
        String seq = txt_seq_cambio.getText();
        String nro_fact = txt_nro_fact.getText();
        String timbra = txt_nro_timbra.getText();
        String estable = "002";
        int tama = 7;

        if (txt_nro_fact.getText().length() < tama) {
            JOptionPane.showMessageDialog(null, "Complete el nro de factura");
        } else {
            Facturas_facturas_26.txt_esta.setText(seq);
            Facturas_facturas_26.lbl_cod.setText(nro_fact);
            Facturas_facturas_26.txt_timbrado.setText(timbra);
            Facturas_facturas_26.txt_sequencia.setText(estable);
         
            this.dispose();
        }


    }//GEN-LAST:event_btn_ok_paraActionPerformed

    private void btn_ok_paraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ok_paraMouseClicked

    }//GEN-LAST:event_btn_ok_paraMouseClicked

    private void txt_nro_factKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nro_factKeyReleased

    }//GEN-LAST:event_txt_nro_factKeyReleased

    private void txt_nro_factKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nro_factKeyPressed

    }//GEN-LAST:event_txt_nro_factKeyPressed

    private void txt_nro_factKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nro_factKeyTyped
        int cant = 7;
        if (txt_nro_fact.getText().length() >= cant) {
            evt.consume();
        }
        char Tecla = evt.getKeyChar();

        if (Tecla == KeyEvent.VK_ENTER) {
            //   btn_ok_para.doClick();
        }
    }//GEN-LAST:event_txt_nro_factKeyTyped

    private void txt_seq_cambioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_seq_cambioKeyTyped
        int cant = 3;
        if (txt_seq_cambio.getText().length() >= cant) {
            evt.consume();
        }
        char Tecla = evt.getKeyChar();

        if (Tecla == KeyEvent.VK_ENTER) {
            txt_nro_fact.requestFocus();
            cargarTxt(txt_seq_cambio.getText());
        }
    }//GEN-LAST:event_txt_seq_cambioKeyTyped

    private void txt_nro_factActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nro_factActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nro_factActionPerformed

    private void txt_seq_cambioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_seq_cambioMouseClicked
        txt_nro_fact.setText("");
        txt_nro_timbra.setText("");
    }//GEN-LAST:event_txt_seq_cambioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(parametro_cambio_26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(parametro_cambio_26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(parametro_cambio_26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(parametro_cambio_26.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                parametro_cambio_26 dialog = new parametro_cambio_26(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {

                        System.exit(0);

                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok_para;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private static javax.swing.JTextField txt_nro_fact;
    private javax.swing.JTextField txt_nro_timbra;
    private static javax.swing.JTextField txt_seq_cambio;
    // End of variables declaration//GEN-END:variables
  public void cargarTxt(String valor) {
        String mostrar = "SELECT nro_fact_ventas,nro_estable_ventas,nro_timbra_ventas FROM ventas_facturacion_surc_26 WHERE  nro_estable_ventas ='" + valor + "'  order by  nro_fact_ventas desc";

        try {

            Connection cn = conectar.getInstance().getConnection();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(mostrar);
            if (rs.next()) {
                String c = rs.getString(1);
                String timbrado = rs.getString(3);
                if (c == null) {
                    txt_nro_fact.requestFocus();
                } else {

                    int j = Integer.parseInt(c);
                    System.out.println(j);
                    GenerarNumero gen = new GenerarNumero();
                    gen.generar(j);
                    txt_nro_fact.setText(gen.serie());
                    txt_nro_timbra.setText(timbrado);

                }
            }

            conectar.getInstance().closeConnection(cn);
        } catch (SQLException ex) {
            Logger.getLogger(parametro_cambio_26.class
                    .getName()).log(Level.SEVERE, null, ex);
        }

    }
}
