/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventas.Modifica_nota;

import Conexion_DB.*;
import Clases.machusculas;
import static Loggin_Principal.Principal.lbl_ventas_usu_ss;
import static Ventas.Modifica_nota.Ventas_venta_modifica.cant_pro_modifica;
import static Ventas.Modifica_nota.Ventas_venta_modifica.cod_pro_modifica;
import static Ventas.Modifica_nota.Ventas_venta_modifica.id_deta_modifica;
import static Ventas.Modifica_nota.Ventas_venta_modifica.tipo_cli_modifica;
import static Ventas.Principal_ventas.lbl_almacen_ventas;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class Ajuste_nota_modifica extends javax.swing.JDialog {

    /**
     * Creates new form Departamentos
     */
    public Ajuste_nota_modifica(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        txtdes.setDocument(new machusculas());
        lbl_ide_deta.setVisible(false);
        tipo_cli.setVisible(false);
        txt_id.setText(cod_pro_modifica);
        txtdes.setText(cant_pro_modifica);
        lbl_ide_deta.setText(id_deta_modifica);
        txt_alma_aju.setText(lbl_almacen_ventas.getText());
        tipo_cli.setText(tipo_cli_modifica);
        ver_pro(cod_pro_modifica);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtdes = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nom = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_alma_aju = new javax.swing.JTextField();
        lbl_ide_deta = new javax.swing.JLabel();
        tipo_cli = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quitar item");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtdes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtdes.setDisabledTextColor(new java.awt.Color(153, 0, 0));
        txtdes.setEnabled(false);
        jPanel1.add(txtdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 80, 30));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon_4/agrega.png"))); // NOI18N
        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 130, 50));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Almacén:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, 30));

        txt_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_id.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_id.setEnabled(false);
        jPanel1.add(txt_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 120, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Cantidad");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Descripción:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 30));

        txt_nom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_nom.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_nom.setEnabled(false);
        jPanel1.add(txt_nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 410, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Stock Actual:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, 30));

        txtstock.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtstock.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtstock.setEnabled(false);
        jPanel1.add(txtstock, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 80, 30));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Id Producto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        txt_alma_aju.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt_alma_aju.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txt_alma_aju.setEnabled(false);
        jPanel1.add(txt_alma_aju, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 120, 30));

        lbl_ide_deta.setText("id");
        jPanel1.add(lbl_ide_deta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 40, 20));

        tipo_cli.setText("tipo");
        jPanel1.add(tipo_cli, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 160));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String cod = txt_id.getText();
        String Cant = txtdes.getText();
        String id = lbl_ide_deta.getText();
        if (tipo_cli.getText().equals("NO")) {
            aumentarstock(cod, Cant);
        } else {
            DescontarstockPedido(cod, Cant);
        }

        try {
            Connection cn = conectar.getInstance().getConnection();
            String eliminarSQL = "DELETE FROM ventas_detalles WHERE id_ven_deta = '" + id + "'";
            PreparedStatement pst = cn.prepareStatement(eliminarSQL);
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "OK");
            Ventas_venta_modifica.btncalcular.doClick();
            this.dispose();
            conectar.getInstance().closeConnection(cn);
        } catch (SQLException | HeadlessException e) {
            // JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ajuste_nota_modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ajuste_nota_modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ajuste_nota_modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ajuste_nota_modifica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ajuste_nota_modifica dialog = new Ajuste_nota_modifica(new javax.swing.JDialog(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_ide_deta;
    private javax.swing.JLabel tipo_cli;
    public static javax.swing.JTextField txt_alma_aju;
    public static javax.swing.JTextField txt_id;
    public static javax.swing.JTextField txt_nom;
    private javax.swing.JTextField txtdes;
    public static javax.swing.JTextField txtstock;
    // End of variables declaration//GEN-END:variables

    void limpiar() {

        txt_id.setText("");
        txt_nom.setText("");
        txtdes.setText("0");
        txtstock.setText("0");

    }

    void ver_pro(String codi) {

        String consul = "SELECT * FROM tienda_productos WHERE  pro_cod='" + codi + "'";
        try {
            Connection cn = conectar.getInstance().getConnection();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(consul);
            while (rs.next()) {
                txtstock.setText(rs.getString(5));
                txt_nom.setText(rs.getString(3));

            }
            conectar.getInstance().closeConnection(cn);
        } catch (Exception e) {
        }

    }

    void aumentarstock(String codi, String can) {
        int des = Integer.parseInt(can);
        String cap = "";
        int desfinal;
        String consul = "SELECT * FROM tienda_productos WHERE  pro_cod='" + codi + "'";
        try {
            Connection cn = conectar.getInstance().getConnection();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(consul);
            while (rs.next()) {
                cap = rs.getString(5);//pendiente a modificacion
            }
            conectar.getInstance().closeConnection(cn);
        } catch (Exception e) {
        }
        desfinal = Integer.parseInt(cap) + des;
        String modi = "UPDATE tienda_productos SET pro_cant='" + desfinal + "' WHERE pro_cod = '" + codi + "'";
        try {
            Connection cn = conectar.getInstance().getConnection();
            PreparedStatement pst = cn.prepareStatement(modi);
            pst.executeUpdate();
            conectar.getInstance().closeConnection(cn);
        } catch (Exception e) {
        }
    }

    void DescontarstockPedido(String codi, String can) {
        int des = Integer.parseInt(can);
        String cap = "";
        int desfinal;
        String consul = "SELECT * FROM tienda_productos WHERE  pro_cod='" + codi + "'";
        try {
            Connection cn = conectar.getInstance().getConnection();
            Statement st = cn.createStatement();
            ResultSet rs = st.executeQuery(consul);
            while (rs.next()) {
                cap = rs.getString(23);//pendiente a modificacion
            }
            conectar.getInstance().closeConnection(cn);
        } catch (Exception e) {
        }
        desfinal = Integer.parseInt(cap) - des;
        String modi = "UPDATE tienda_productos SET pro_alma='" + desfinal + "' WHERE pro_cod = '" + codi + "'";
        try {
            Connection cn = conectar.getInstance().getConnection();

            PreparedStatement pst = cn.prepareStatement(modi);
            pst.executeUpdate();
            conectar.getInstance().closeConnection(cn);
        } catch (Exception e) {
        }
    }

}
